### ISSUE TITLE
How to debug root cause for core dump during starkit execution

### ISSUE THREAD

**Issue by madhurkashyap** [tclssg/packer#1]
Hello,

I created a utility for x86_64 architecture using the contents of packer employing both sdx and tclkit bundles. It causes crash during execution with following information printed on the shell

PELICAN-INFO: Job started on lc1271 at Thu Sep 07 22:26:35 IST 2017
PELICAN-INFO: Initializing liberty files
Thu Sep 07 22:26:49 IST 2017 Start slurping /proj/tdk/early_access/GF_C040LP_SNPS_LOG_12TM2_GO1_H/GF_C040LP_SNPS_LOG_12TM2_GO1_H_d1.01.00.04/gf40npkhsst/TIMING/ecsm/gf40npkhsst_PssV0700W0700G0000S0000Tm20.lib
Segmentation fault (core dumped)

I am unable to understand root-cause behind this and how to debug this problem. Kindly help.

Thanks,
Madhur

**Comment by dbohdan** [comment]
Hi. I can't tell much from the log. Those messages didn't come from Packer or [KitCreator](http://kitcreator.rkeene.org/fossil/home). Did you use the Tclkits included in this repo or substitute your own? Have you tried building a Starpack [manually](https://tcl.wiki/14080)?

**Comment by madhurkashyap** [comment]
Hi Bohdan,

The messages are from the application I have written. I just wanted to mention what kind of stack trace gets printed when segmentation fault happens. I do have core files but I could not debug much in them.

I have used the tclkits provided in tclssg/packer. Kindly suggest a way out of this.

Thanks,
Madhur

**Comment by dbohdan** [comment]
I'll need more information to tell whether a part of Packer (either a packaged Tclkit or the startup script) is causing the issue you're seeing.
1. What is your OS? I assume it's Linux because `x86_64` is primarily a Linux term, but I would like to know the distribution and the release.
1. Does your application include binary extensions?
1. Can you run the Tclkit itself without it segfaulting?
1. Build a Tclkit for your system with [KitCreator's online interface](http://kitcreator.rkeene.org/kitcreator) and package your application with it. Does it still segfault?

**Comment by madhurkashyap** [comment]
Linux lvd5433 2.6.18-348.1.1.el5 #1 SMP Fri Dec 14 05:25:59 EST 2012 x86_64 x86_64 x86_64 GNU/Linux
These are RHEL5 servers.

Application contains only Tcl code but uses thread, zlib and OOPs

Tclkit -- This gets me a tcl shell where I can perform regular operations. But if I try to run my program with tclkit it gives a segv whether as a starkit or the way below

unix> tclkit-8.6.3-rhel5-x86_64 pelican.tcl -caseSuite test.def -libs "gf40npkhsst_PssV0700W0700G0000S0000Tm20.lib.gz"

Thanks for sharing the online tclkit creation system. Queue has reasonable waiting time. I am trying to build one at my end using 0.10.2 version of kitcreator but unable to build Tcl. 

Unless I am able to debug the root-cause for core-dump, there is guarantee that everything would work out as expected.

**Comment by madhurkashyap** [comment]
Compiling a tclkit on servers I work with resolved the crash issue. Thanks for helping me out.

**Comment by madhurkashyap** [comment]
I tried to move to 8.6.5 but kitcreator has a known issue I suppose that starkit creation with this tclkit fails.
=============================
~266$ ./tclkit-8.6.5-rhel5-x86_64 sdx-20110317.kit wrap pelican -runtime tclkit-8.6.5-rhel5-x86_64.temp
can't find package vfs::mkcl
    while executing
"package require vfs::mkcl"
    (procedure "::vfs::mk4::Mount" line 4)
    invoked from within
"::vfs::mk4::Mount /sync/cache/pef/clc/s1c/s1c6045e0e8c11d1e-1.1-1502883666-0 /sync/cache/pef/clc/s1c/s1c6045e0e8c11d1e-1.1-1502883666-0 -readonly"
    ("eval" body line 1)
    invoked from within
"eval [list ::vfs::${driver}::Mount $self $self] $args"
=====================================================

With 8.6.3 I repeatedly get segv. In short I once again got stuck. Can you help a bit more?

Thanks
Madhur

**Comment by dbohdan** [comment]
I am not sure what is the exact cause is here, but it looks like you might not be building the Tclkit with Metakit support and with Metakit as storage. Look at your build log to see if that's the case.
